Repository viadonau/Pegelhub-Core, pull requests merged in 2024-04, with the labels that each got.

#5 PGL-5 updated README.md
  pegelhub-iec-connector/README.md
Labels: documentation

#6 PGL-25: added pegelhub-tstp-connector
  pegelhub-tstp-connector/.gitignore
  pegelhub-tstp-connector/README.md
  pegelhub-tstp-connector/pom.xml
  pegelhub-tstp-connector/src/main/java/com/stm/pegelhub/connector/tstp/Main.java
Labels: enhancement

#7 PGL-21: change ftp connector file parsing logic
  pegelhub-ftp-connector/src/main/java/com/stm/pegelhub/connector/ftp/FtpTask.java
Labels: bug

#8 PGL-6: rework README.md
  pegelhub-core/README.md
Labels: documentation

#9 PGL-37: Use FTP-Filter with correct lookback time
  pegelhub-ftp-connector/src/main/java/com/stm/pegelhub/connector/ftp/FtpTask.java
Labels: enhancement

#10 PGL-38: Adjust InfluxDB schema
  pegelhub-ftp-connector/src/main/java/com/stm/pegelhub/connector/ftp/FtpTask.java
  pegelhub-library/src/main/java/com/stm/pegelhub/lib/internal/HttpPegelHubCommunicator.java
Labels: enhancement
